gateway_url = {'forsyth': 'https://forsyth.itslearning.com/Index.aspx'}
root_url = {
    'forsyth': 'https://forsyth.itslearning.com'
}

resource_url = 'https://resource.itslearning.com'

autologin_url = '{}/elogin/autologin.aspx'
course_list = '{}/Course/AllCourses.aspx'
course_base_url = '{}/ContentArea/ContentArea.aspx?LocationID={}&LocationType={}'
login_landing_page = '{}/DashboardMenu.aspx'
course_bulletin_base_url = '{}/Course/course.aspx?CourseId='
project_bulletin_base_url = '{}/Project/project.aspx?ProjectId={}&BulletinBoardAll=True'
bulletin_next_url = '{}/Bulletins/Page?courseId={}&boundaryLightBulletinId={}&boundaryLightBulletinCreatedTicks={}'
folder_base_url = '{}/Folder/processfolder.aspx?FolderID='
file_base_url = '{}/File/fs_folderfile.aspx?FolderFileID='
assignment_base_url = '{}/essay/read_essay.aspx?EssayID='
note_base_url = '{}/note/View_Note.aspx?NoteID='
discussion_base_url = '{}/discussion/list_discussions.aspx?DiscussionID='
weblink_base_url = '{}/weblink/weblink.aspx?WebLinkID='
weblink_header_base_url = '{}/weblink/weblink_header.aspx?WebLinkID='
learning_tool_base_url = '{}/LearningToolElement/ViewLearningToolElement.aspx?LearningToolElementId='
comment_service = '{}/Services/CommentService.asmx/GetOldComments?sourceId={}&sourceType={}&commentId={}&count={}&numberOfPreviouslyReadItemsToDisplay={}&usePersonNameFormatLastFirst={}'
not_found = '{}/not_exist.aspx'
test_base_url = '{}/test/view_survey_list.aspx?TestID='
old_messaging_api_url = '{}/Messages/InternalMessages.aspx?MessageFolderId={}'
picture_url = '{}/picture/view_picture.aspx?PictureID={}&FolderID=-1&ChildID=-1&DashboardHierarchyID=-1&DashboardName=&ReturnUrl='
online_test_url = '{}/Ntt/EditTool/ViewTest.aspx?TestID={}'
online_test_details_postback_url = '{}/Ntt/EditTool/ViewTestResults.aspx?TestResultId={}'
new_messaging_api_url = '{}/restapi/personal/instantmessages/messagethreads/v1?threadPage={}'
all_projects_url = '{}/Project/AllProjects.aspx'
base64_png_image_url = '{}data:image/png;base64,'
base64_jpeg_image_url = '{}data:image/jpeg;base64,'
unauthorized_url = '{}/not_authorized.aspx'
